service: openfaas-integration

provider:
  name: openfaas
  gateway: http://127.0.0.1:8080

functions:
  hello-openfaas:
    runtime: node
    handler: ./hello-openfaas
    image: hello-openfaas

plugins:
  - serverless-openfaas